# (no "version:" key needed with Compose v2)
services:
  mongo:
    image: mongo:7
    volumes: ["mongo_data:/data/db"]
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost:27017", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    image: artium777/simple-mongo-app:${GIT_SHA}
    ports: ["8000:8000"]
    environment:
      MONGO_URL: "mongodb://mongo:27017"
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 5

volumes:
  mongo_data:
