services:
  app:
    image: artium777/simple-mongo-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, json, urllib.request as u; sys.exit(0 if json.load(u.urlopen('http://127.0.0.1:8000/health'))['status']=='ok' else 1)"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
