services:
  app:
    image: artium777/simple-mongo-app:latest
    container_name: simple-mongo-app
    environment:
      - MONGO_URL=mongodb://mongo:27017/people
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health | grep -q 'ok'"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: simple-mongo-mongo
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  mongo_data:
