apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: simple-mongo
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
